modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT, https://spdx.org/licenses/MIT.html"
issueTrackerURL="https://github.com/Endgineer/tinkers-levelling-addon-pbc"

[[mods]]
modId="pritheebecareful"
version="${version}"
displayName="Prithee Be Careful"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-levelling-addon/"
logoFile="logo.png"
authors="Pyre540"
description='''
I don't want to see me work squandered.
'''

[[dependencies.pritheebecareful]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pritheebecareful]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.pritheebecareful]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tinkers_range}"
    ordering="AFTER"
    side="BOTH"


[[dependencies.pritheebecareful]]
    modId="create"
    mandatory=true
    versionRange="[6.0.6,)"
    ordering="AFTER"
    side="BOTH"


[[dependencies.pritheebecareful]]
    modId="curseoftheabyss"
    mandatory=false
    versionRange="[1.20.1-2.3.0,)"
    ordering="AFTER"
    side="BOTH"
